services:
  ticketslave:
    image: chris482/ticketslave:latest
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./data:/data
    environment:
      - DATA_DIR=/data
    restart: unless-stopped
